version: '3.8'

services:
  # PostgreSQL for structured data
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: syncsphere
      POSTGRES_USER: syncsphere
      POSTGRES_PASSWORD: syncsphere_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U syncsphere"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MongoDB for audio metadata and flexible data
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: syncsphere
      MONGO_INITDB_ROOT_USERNAME: syncsphere
      MONGO_INITDB_ROOT_PASSWORD: syncsphere_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
