# OpenDAW Collaboration System - Development Setup
# 
# This docker-compose file is optimized for development:
# - Hot reload for all services
# - Debug ports exposed
# - Volume mounts for source code
# - Development tools included
#
# Usage:
#   docker-compose -f docker-compose.dev.yml up -d
#   docker-compose -f docker-compose.dev.yml logs -f

services:
  # Database (same as production)
  postgres:
    image: postgres:15-alpine
    container_name: opendaw_postgres_dev
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: opendaw
      POSTGRES_PASSWORD: collaboration
      POSTGRES_DB: opendaw_collab
    ports:
      - "5434:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./opendaw-collab-mvp/src/database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opendaw"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (same as production)
  redis:
    image: redis:7-alpine
    container_name: opendaw_redis_dev
    env_file:
      - .env.docker
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data

  # Collaboration Server (development mode)
  collaboration:
    image: node:18-alpine
    container_name: opendaw_collaboration_dev
    working_dir: /app
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DATABASE_URL=postgresql://opendaw:collaboration@postgres:5432/opendaw_collab
      - REDIS_URL=redis://redis:6379
      - WS_PORT=3005
      - HTTP_PORT=3003
    ports:
      - "3004:3003"
      - "3005:3005"
      - "9229:9229"  # Debug port
    volumes:
      - ./opendaw-collab-mvp:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped

  # SynxSphere Dashboard (development mode)
  synxsphere:
    image: node:18-alpine
    container_name: opendaw_synxsphere_dev
    working_dir: /app
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=development
    ports:
      - "8000:3000"
      - "9230:9230"  # Debug port
    volumes:
      - .:/app
      - /app/node_modules
      - /app/openDAW
      - /app/opendaw-collab-mvp
    depends_on:
      - collaboration
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped

  # OpenDAW Studio (development mode - served by Vite)
  opendaw:
    image: node:18-alpine
    container_name: opendaw_studio_dev
    working_dir: /app/studio
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--experimental-global-webcrypto
      - VITE_API_URL=http://localhost:3004/api
      - VITE_WS_URL=ws://localhost:3005
      - VITE_SYNXSPHERE_URL=http://localhost:8000
      - DATABASE_URL=postgresql://opendaw:collaboration@postgres:5432/opendaw_collab
      - REDIS_URL=redis://redis:6379
      - WS_PORT=3005
      - HTTP_PORT=3003
    ports:
      - "8080:8080"  # Vite dev server
      - "9231:9231"  # Debug port
    volumes:
      - ./openDAW:/app
      - ./start-opendaw-http.sh:/app/start-opendaw-http.sh
      - /app/node_modules
    depends_on:
      - collaboration
    command: sh -c "cd /app/studio && /app/start-opendaw-http.sh"
    restart: unless-stopped

  # Development tools
  adminer:
    image: adminer:latest
    container_name: opendaw_adminer_dev
    env_file:
      - .env.docker
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  default:
    name: opendaw_dev_network
