#!/bin/bash

echo "🧪 Testing Timeline Update Sync System"
echo "======================================"
echo ""
echo "📋 Test Steps:"
echo "1. Open two browser windows (one incognito)"
echo "2. Login with different accounts"
echo "3. Join the same room"
echo "4. In Browser 1: Create a track by dragging an audio sample"
echo "5. In Browser 1: Change track volume, pan, or other parameters"
echo "6. Verify Browser 2 receives and applies the updates"
echo ""
echo "🔍 What to look for in console:"
echo "- [UpdateSync] Starting timeline synchronization..."
echo "- [UpdateSync] Local update detected: new/primitive/pointer"
echo "- [UpdateSync] Sending batch of X updates"
echo "- [UpdateSync] Remote updates received: X"
echo "- [UpdateSync] Applying update: ..."
echo ""
echo "📊 Expected Results:"
echo "- Track creation should sync (NewUpdate)"
echo "- Parameter changes should sync (PrimitiveUpdate)"
echo "- Track deletion should sync (DeleteUpdate)"
echo ""
echo "⚠️  Known Limitations:"
echo "- Audio files need separate sync (Phase 3)"
echo "- UI states need separate sync (Phase 4)"
echo "- No permission checking yet"
echo ""
echo "Press Enter to continue..."
read

# Start the services
echo "🚀 Starting services..."
cd /d/SyncSphere
docker-compose -f docker-compose.dev.yml up -d

echo ""
echo "✅ Services started!"
echo "🌐 Open: https://localhost:8443"
echo ""
echo "📝 Debug commands:"
echo "- window.syncSphereTimelineSync - Access the sync instance"
echo "- window.syncSphereAudioSync - Access the audio sync instance" 