services:
  postgres:
    image: postgres:15
    container_name: opendaw_collab_db
    environment:
      POSTGRES_USER: opendaw
      POSTGRES_PASSWORD: collaboration
      POSTGRES_DB: opendaw_collab
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/database/02-init-additional-dbs.sh:/docker-entrypoint-initdb.d/02-init-additional-dbs.sh
      - ./src/database/init-databases.sh:/docker-entrypoint-initdb.d/02-init-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opendaw"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: opendaw_collab_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
